### ISSUE TITLE
KODI and Octopus NET No EGP

### ISSUE THREAD

**Issue by Ernst-Frutiger** [DigitalDevices/pvr.octonet#11]
KODI 17 wirh a Octopus NET no EGP available. TV works fine inlcuding HD, including CI.
Can sobody help me. Is there a solution.
Home base ist Switzerland, Town Solothurn.

**Comment by julianscheel** [comment]
@Ernst-Frutiger Is EPG information available on the EPG page of the Octopus NET's web interface? What OS are you running on?

**Comment by Ernst-Frutiger** [comment]
Good morning

Yes in the Octopus NET V2 are EGP-Information available.

I run KODI with Windows and as well with Android. Both I can see all TV-Channels, but no EGP.

Kind regards
Ernst





----------------------------------
Ernst Frutiger
Überführungsstrasse 14
4565 Recherswil / Switzerland

Phone: +41 (32) 675 33 56
E-Mail: ernst.frutiger@gawnet.ch<mailto:ernst.frutiger@gawnet.ch>

Von: Julian Scheel [mailto:notifications@github.com]
Gesendet: Dienstag, 23. Mai 2017 09:03
An: DigitalDevices/pvr.octonet <pvr.octonet@noreply.github.com>
Cc: Ernst-Frutiger <ernst.frutiger@gawnet.ch>; Mention <mention@noreply.github.com>
Betreff: Re: [DigitalDevices/pvr.octonet] KODI and Octopus NET No EGP (#11)


@Ernst-Frutiger<https://github.com/ernst-frutiger> Is EPG information available on the EPG page of the Octopus NET's web interface? What OS are you running on?

**Comment by dennis-hamester** [comment]
@Ernst-Frutiger Can you upload a Kodi log from a session where you opened the channel browser with the missing EPG entries?

**Comment by IQLiving** [comment]
Hallo,

bzgl. Dieses Problems hatte ich bereits am 2 Januar 2017 ein Ticket bei Digital Devices eröffnet, da hieß es das Problem ist nachstellbar und es wird dran gearbeitet !, nun ist der 18 Juni!

wenn das Problem (Plattform unabhängig) nachstellbar ist wieso werden dann noch Logfiles benötigt ?

Grüße
iqliving

**Comment by julianscheel** [comment]
We've just fixed an issue (https://github.com/DigitalDevices/pvr.octonet/commit/020dd98e7b37dfa02f68fe343561f7dfe73e074d), which caused all EPG events to be mapped to one channel under certain circumstances. Namedly whenever the satellite list name contained non-numeric characters.
@Ernst-Frutiger @IQLiving Could you please test if this solves the problem for you as well?
If you're running on Windows you can download the updated plugin directly from AppVeyor: https://ci.appveyor.com/project/julianscheel/pvr-octonet/build/Krypton-6ee2847-2017-07-06/artifacts
For Linux you'd either have to wait for the next nightly or build the plugin yourself.

**Comment by IQLiving** [comment]
Windows OK
Linux (Libreelec 9.0) OK

many Thanks

**Comment by julianscheel** [comment]
@IQLiving Thanks for testing.
Issue closed.
