### ISSUE TITLE
PVR Backend not available in Kodi 17.2

### ISSUE THREAD

**Issue by hitam4450** [DigitalDevices/pvr.octonet#12]
Hi, I just upgraded KODI 17.1 to KODI 17.2 on one of my machines and found out, the the Digitaldevices PVR Backend is no longer available . What happened to it and how to get it back into KODI 17.2 to access my OCTOPUSNet ?

KODI 17.1 was installed from the http://ppa.launchpad.net/team-xbmc/ppa/ubuntu/ repository.

regards, hitam4450

**Comment by julianscheel** [comment]
It appears our travis build job died and did not inform us that there is some api breakage for 17.2 which would have required us to tag a new version. I'll investigate this further on friday.
Sorry for the inconvenience.

**Comment by hitam4450** [comment]
OK and thank you° I can live without it until friday! :smile: :thumbsup:

regards, hitam4450

**Comment by julianscheel** [comment]
@hitam4450 What platform are you on? I just checked for Windows and the Ubuntu ppa and the Krypton (now 17.3) builds do contain the Octonet plugin. The build error I saw was unrelated and not an API breakage as I initially assumed.

**Comment by hitam4450** [comment]
I am on UBUNTU 16.04, I just read the release from KODI 17.3 that missing PVR's should be included again. I will try later and verify. I'll get back to you!

**Comment by hitam4450** [comment]
I just installed KODI 17.3 and the PVR add-on from Digitalevices is not available in the PVR section and neither from the repository as it used to be in KODI 17.1 !! Its a shame!

regards, hitam4450

**Comment by julianscheel** [comment]
@hitam4450 From which source are you installing kodi? In the official team-xbmc ppa (https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa) the octonet-pvr addon is included. Just make sure to actually install it (￼kodi-pvr-octonet version). I don't see an obvious reason why it should not work.

**Comment by hitam4450** [comment]
I am on UBUNTU 16.04, I just read the release from KODI 17.3 that missing PVR's should be included again. I will try later and verify. I'll get back to you!

**Comment by hitam4450** [comment]
I installed from the source mentioned, for whatever reason the kodi-pvr-ocotonet package did not get installed by default! Many thanks for your support! Everything works fine now and I am able to Access my OCTONET Server!

regards, hitam4450
