### ISSUE TITLE
Kodi PVR plugin on Kodi 17 or 18 zapping issues

### ISSUE THREAD

**Issue by alturismo** [DigitalDevices/pvr.octonet#18]
issues on zapping channels, tested devices, windows, linux, andoid (nvidia shield),
as playlist with vlc is always fine i think i can exept tuning or CI for encrypted channels, all good,
also as network tuner for tvheadend its always working with 0 issues, so to me its a kodi pvr plugin issue.

as its not exactly reproduce able a little hard to tell, always when zapping it starts to completely freeze,
nvm wich platform, nvm if fta or encrypted channels, nvm if 720p or 1080i, ...

a sample from windows kodi log

09:37:32.691 T:16348  NOTICE: DXVA::CProcessorHD::InitProcessor: Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:yes.
09:37:45.194 T:16348  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Alle Kanäle/pvr.octonet_1003.pvr
09:37:45.221 T:7720  NOTICE: Creating InputStream
09:37:45.236 T:16348   ERROR: DXVA::CProcessorHD::GetInputView: cannot get decoder view.
09:37:45.236 T:16348   ERROR: Previous line repeats 1 times.
09:37:45.236 T:16348   ERROR: DXVA::CProcessorHD::Render: incomplete views set.
09:37:45.240 T:7720  NOTICE: Creating Demuxer
09:37:45.253 T:16348   ERROR: DXVA::CProcessorHD::GetInputView: cannot get decoder view.
09:37:45.253 T:16348   ERROR: Previous line repeats 1 times.
09:37:45.253 T:16348   ERROR: DXVA::CProcessorHD::Render: incomplete views set.
09:37:45.269 T:16348   ERROR: DXVA::CProcessorHD::GetInputView: cannot get decoder view.
09:37:45.269 T:16348   ERROR: Previous line repeats 1 times.
09:37:45.269 T:16348   ERROR: DXVA::CProcessorHD::Render: incomplete views set.
09:37:45.286 T:16348   ERROR: DXVA::CProcessorHD::GetInputView: cannot get decoder view.
09:37:45.286 T:16348   ERROR: Previous line repeats 1 times.
09:37:45.286 T:16348   ERROR: DXVA::CProcessorHD::Render: incomplete views set.
....
09:39:15.428 T:7720   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, pvr://channels/tv/Alle Kanäle/pvr.octonet_1003.pvr
09:39:38.492 T:16348  NOTICE: CVideoPlayer::CloseFile()
09:39:38.492 T:16348  NOTICE: VideoPlayer: waiting for threads to exit
09:39:45.424 T:7720   ERROR: CDVDDemuxFFmpeg::Open - error probing input format, pvr://channels/tv/Alle Kanäle/pvr.octonet_1003.pvr
09:39:45.424 T:7720   ERROR: CVideoPlayer::OpenDemuxStream - Error creating demuxer
09:39:45.424 T:7720  NOTICE: CVideoPlayer::OnExit()
09:39:45.424 T:7720  NOTICE: Closing stream player 1
09:39:45.424 T:7720  NOTICE: Waiting for audio thread to exit
09:39:45.430 T:13856  NOTICE: thread end: CVideoPlayerAudio::OnExit()
09:39:45.430 T:7720  NOTICE: Closing audio device
09:39:45.430 T:7720  NOTICE: Deleting audio codec
09:39:45.430 T:7720  NOTICE: Closing stream player 2
09:39:45.431 T:7720  NOTICE: waiting for video thread to exit
09:39:45.431 T:1736   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
09:39:45.431 T:1736  NOTICE: thread end: video_thread
09:39:45.431 T:7720  NOTICE: deleting video codec
09:39:45.433 T:7720  NOTICE: DXVA::CDecoder::Close: closing decoder.
09:39:45.433 T:7720  NOTICE: DXVA: closing decoder context.
09:39:45.433 T:7720  NOTICE: Closing stream player 4
09:39:45.433 T:7720  NOTICE: waiting for teletext data thread to exit
09:39:45.433 T:16164   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true (-1)
09:39:45.433 T:16164  NOTICE: thread end: data_thread
09:39:45.434 T:7720  NOTICE: Closing stream player 3
09:39:45.436 T:16348  NOTICE: VideoPlayer: finished waiting
09:39:45.440 T:16348  NOTICE: CVideoPlayer::CloseFile()
09:39:45.440 T:16348  NOTICE: VideoPlayer: waiting for threads to exit
09:39:45.440 T:16348  NOTICE: VideoPlayer: finished waiting

**Comment by ksooo** [comment]
Kodi 17 and 18 ist history for long time. Let's close this issue. In case it is still a problem with latest addon release, please open a new issue.
