### ISSUE TITLE
not all epg data fetched

### ISSUE THREAD

**Issue by ksooo** [DigitalDevices/pvr.octonet#2]
epg data missing for some channels. see screenshots:

![screen shot 2016-11-11 at 12 38 10](https://cloud.githubusercontent.com/assets/3226626/20214027/ddf6745c-a80b-11e6-85c9-92e8f3642771.png)
![screenshot004](https://cloud.githubusercontent.com/assets/3226626/20214028/ddf99718-a80b-11e6-9768-7c6d9508ab04.png)

**Comment by ksooo** [comment]
octopus firmware version is 1.0.72, if that helps

**Comment by julianscheel** [comment]
Thanks, I could reproduce it on Windows, but not on Linux.
Looking into it...

**Comment by dennis-hamester** [comment]
@ksooo Can you test the most recent commit? The missing EPG data should now be fixed. We will release a 0.3.3 version with this fix if it works on your end.

**Comment by ksooo** [comment]
Confirming the fix. Can not say for sure whether all channels that have to have epg data now actually have, but the channel i spotted (the first channel in channel list) now has.

**Comment by dennis-hamester** [comment]
Great. I have tagged version 0.3.3, which will be included in upstream Kodi once xbmc/repo-binary-addons#36 gets merged.
