### ISSUE TITLE
Radio Channels not in the right folder in KODI 18.2

### ISSUE THREAD

**Issue by AirSATBE** [DigitalDevices/pvr.octonet#30]
Hi All,

I have a question as i'm starting using the Digital devices octopus device which is working great with a Formuler z8 device and KODI 18.2 installed on it.

I only have 2 issues (the other issue will be created in a separate topic), first issue is that radio channels do appear in TV channels. The radio channels in KODI is hence empty.

This is probably due because the Octopus cast tool that i'm using hasn't generated the JSON file 100% in line with the requirements of KODI 18.2 I believe.

Here below is a copy/paste of my JSON file.

Thanks very much for your help!

{"GroupList":[{"Title":"Default","ChannelList":[{"Title":"La Une HD","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 351, 551, 34,101, 51&x_pmt=351&x_ci=1","Tracks":[34,101],"ID":"0130:318:12100:16910","Radio":false,"NoEPG":false},{"Title":"La Deux","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 352, 552, 102,122, 52&x_pmt=352&x_ci=1","Tracks":[102,122],"ID":"0130:318:12100:16911","Radio":false,"NoEPG":false},{"Title":"La Trois","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 353, 553, 103,123, 53&x_pmt=353&x_ci=1","Tracks":[103,123],"ID":"0130:318:12100:16912","Radio":false,"NoEPG":false},{"Title":"RTL-TVi HD","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 356, 556, 106, 0&x_pmt=356&x_ci=1","Tracks":[106],"ID":"0130:318:12100:16913","Radio":false,"NoEPG":false},{"Title":"Club-RTL","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 357, 557, 107, 0&x_pmt=357&x_ci=1","Tracks":[107],"ID":"0130:318:12100:16914","Radio":false,"NoEPG":false},{"Title":"Plug-RTL","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 358, 558, 108, 0&x_pmt=358&x_ci=1","Tracks":[108],"ID":"0130:318:12100:16915","Radio":false,"NoEPG":false},{"Title":"AB3","Request":"?src=1&fe=2&freq=12515&pol=h&sr=22000&msys=dvbs&pids=0, 2202, 602, 142, 0&x_pmt=2202&x_ci=1","Tracks":[142],"ID":"0192:53:1105:4102","Radio":false,"NoEPG":false},{"Title":"TF1 HD","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 510, 511, 512,513,514, 0&x_pmt=510&x_ci=1","Tracks":[512,513,514],"ID":"0130:319:15900:301","Radio":false,"NoEPG":false},{"Title":"France 2 HD","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 520, 521, 522,523,524, 0&x_pmt=520&x_ci=1","Tracks":[522,523,524],"ID":"0130:319:15900:302","Radio":false,"NoEPG":false},{"Title":"France 3","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 530, 531, 532,534, 536&x_pmt=530&x_ci=1","Tracks":[532,534],"ID":"0130:319:15900:303","Radio":false,"NoEPG":false},{"Title":"France 4","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 640, 641, 642,643,644, 646&x_pmt=640&x_ci=1","Tracks":[642,643,644],"ID":"0130:319:15900:314","Radio":false,"NoEPG":false},{"Title":"France 5","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 550, 551, 552,554, 555&x_pmt=550&x_ci=1","Tracks":[552,554],"ID":"0130:319:15900:305","Radio":false,"NoEPG":false},{"Title":"Arte HD","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 570, 571, 572,573,574,577, 0","Tracks":[572,573,574,577],"ID":"0130:319:15900:307","Radio":false,"NoEPG":false},{"Title":"TFX","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 610, 611, 612, 616&x_pmt=610&x_ci=1","Tracks":[612],"ID":"0130:319:15900:311","Radio":false,"NoEPG":false},{"Title":"AB1","Request":"?src=1&freq=12692&pol=h&sr=27500&msys=dvbs2&pids=0, 402, 102, 202,302, 502&x_pmt=402&x_ci=1","Tracks":[202,302],"ID":"0130:319:9900:452","Radio":false,"NoEPG":false},{"Title":"DISNEY CHANNEL","Request":"?src=1&fe=2&freq=12207&pol=v&sr=29700&msys=dvbs2&pids=0, 700, 710, 721,722,723, 0&x_pmt=700&x_ci=1","Tracks":[721,722,723],"ID":"0192:1:1090:9007","Radio":false,"NoEPG":false},{"Title":"DISNEY CHANNEL+1","Request":"?src=1&fe=2&freq=12090&pol=v&sr=29700&msys=dvbs2&pids=0, 800, 810, 821,822, 841&x_pmt=800&x_ci=1","Tracks":[821,822],"ID":"0192:1:1084:9408","Radio":false,"NoEPG":false},{"Title":"TV5MONDE EUROPE","Request":"?src=1&freq=11137&pol=h&sr=27500&msys=dvbs&pids=0, 719, 3522, 3642, 3602","Tracks":[3642],"ID":"0130:318:13100:7322","Radio":false,"NoEPG":false},{"Title":"Al Jazeera English HD","Request":"?src=1&freq=11137&pol=h&sr=27500&msys=dvbs&pids=0, 267, 3506, 3626,3686, 0","Tracks":[3626,3686],"ID":"0130:318:13100:7306","Radio":false,"NoEPG":false},{"Title":"France 24 HD (en","Request":"?src=1&freq=11566&pol=h&sr=29900&msys=dvbs2&pids=0, 807, 817, 827,837, 0","Tracks":[827,837],"ID":"0130:318:15300:807","Radio":false,"NoEPG":false},{"Title":"France 24 HD (in","Request":"?src=1&freq=11566&pol=h&sr=29900&msys=dvbs2&pids=0, 808, 818, 828,838, 0","Tracks":[828,838],"ID":"0130:318:15300:808","Radio":false,"NoEPG":false},{"Title":"BBC World News","Request":"?src=1&freq=12597&pol=v&sr=27500&msys=dvbs&pids=0, 1027, 163, 92, 0","Tracks":[92],"ID":"0130:318:9400:8204","Radio":false,"NoEPG":false},{"Title":"Euronews","Request":"?src=1&freq=12597&pol=v&sr=27500&msys=dvbs&pids=0, 1034, 2221, 2232, 768","Tracks":[2232],"ID":"0130:318:9400:8211","Radio":false,"NoEPG":false},{"Title":"Bel RTL","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 369, 0, 119, 119&x_pmt=369&x_ci=1","Tracks":[119],"ID":"0130:318:12100:16922","Radio":true,"NoEPG":false},{"Title":"Classic21","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 362, 0, 112, 112&x_pmt=362&x_ci=1","Tracks":[112],"ID":"0130:318:12100:16917","Radio":true,"NoEPG":false},{"Title":"La Premiere","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 365, 0, 115, 115&x_pmt=365&x_ci=1","Tracks":[115],"ID":"0130:318:12100:16920","Radio":true,"NoEPG":false},{"Title":"Mint","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 368, 0, 118, 118&x_pmt=368&x_ci=1","Tracks":[118],"ID":"0130:318:12100:16921","Radio":true,"NoEPG":false},{"Title":"Musiq 3","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 364, 0, 114, 114&x_pmt=364&x_ci=1","Tracks":[114],"ID":"0130:318:12100:16919","Radio":true,"NoEPG":false},{"Title":"Pure FM","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 361, 0, 111, 111&x_pmt=361&x_ci=1","Tracks":[111],"ID":"0130:318:12100:16916","Radio":true,"NoEPG":false},{"Title":"Radio Contact","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 370, 0, 120, 120&x_pmt=370&x_ci=1","Tracks":[120],"ID":"0130:318:12100:16923","Radio":true,"NoEPG":false},{"Title":"VivaCite","Request":"?src=1&freq=10930&pol=h&sr=30000&msys=dvbs2&pids=0, 363, 0, 113, 113&x_pmt=363&x_ci=1","Tracks":[113],"ID":"0130:318:12100:16918","Radio":true,"NoEPG":false}]}]}

**Comment by ksooo** [comment]
Please use the Kodi forum for support requests. https://forum.kodi.tv/
