### ISSUE TITLE
Format some TV Channels 4:3 instead of 16:9

### ISSUE THREAD

**Issue by AirSATBE** [DigitalDevices/pvr.octonet#31]
Hi All,

I'm starting using Octopus device which is working great with KODI 18.2 installed on the client side.
However, i notice that some channels do appear rightly (16:9 format), but some others (please refer to the picture) are in 4:3 format. I presume this is not an issue from the octopus device as the channel is probably broadcasted in 4:3, however if i look at this channel from a normal SAT set-top box, it does appear in 16:9. The set-top box probably enlarge the format for a better user experience, but i'm wondering if Octopus device could do the same.

I noticed this issue on this channel:
{"Title":"France 4","Request":"?src=1&freq=11681&pol=h&sr=27500&msys=dvbs2&pids=0, 640, 641, 642,643,644, 646&x_pmt=640&x_ci=1","Tracks":[642,643,644],"ID":"0130:319:15900:314","Radio":false,"NoEPG":false}

Channel France 4 on Hotbird 13° Est:
https://fr.kingofsat.net/detail-france4.php

I've noticed this on some other channels. Out of the belgian and french channels, 50% approximately are in the right format (16:9) and the others are in the 'wrong format' 4:3.

Thanks for the help!

![IMG_20190810_171250](https://user-images.githubusercontent.com/53991090/62831174-59e79980-bc1b-11e9-8548-7adf23a6a6a2.jpg)

**Comment by ksooo** [comment]
Let's close this old issue. If it still is a problem with latest Kodi/Add-on version, please open a new issue.
