### ISSUE TITLE
How to build in LINUX (DEBIAN) for KODI

### ISSUE THREAD

**Issue by hitam4450** [DigitalDevices/pvr.octonet#4]
Hi,
I would love to use your extension on my DEBIAN Jessie 8.5 system including kodi 16.1.

How to compile / install your extension ??

I really appreciate your detailed instruction to get me in a position to install and use your extension!

regards, hitam4450

**Comment by dennis-hamester** [comment]
I will update the readme with instructions to build the plugin under Linux. However, Kodi 16 is not supported. You have to upgrade to Kodi 17. Beta 5 might work, but I'm not sure. We have seen several problems with some Kodi beta versions. Ideally, use a recent version built from git.

**Comment by dennis-hamester** [comment]
I have updated the README.md. The instructions should work for both Linux and Windows now. But keep in mind that this plugin won't work with Kodi 16.

**Comment by hitam4450** [comment]
@Dennis: Thank you for your support and help !!
