### ISSUE TITLE
Cannot play any channels on DEBIAN

### ISSUE THREAD

**Issue by hitam4450** [DigitalDevices/pvr.octonet#5]
Hi,

i do run Kodi17.0 on my ANDROID device. i enabled the digitaldevice client and configured the network address of the OCTOPUSNET server. After that I turned to the WebIf of the OCTOPUSNET (version 1.0.55) and downloaded System Channel List from the net and uploaded this list onto the OCTOPUSNEt server and reboot! The client in KODI complains "no channels available"..

What happened and how to correct the problem!

regards, hitam4450

**Comment by julianscheel** [comment]
What firmware version is your OctopusNET running with?
Did you try to let the OctopusNET do a channel scan instead of uploading a predefined list?
And finally, could you please paste what your OctopusNET returns when opening the following URL in your browser:
`http://*youroctonetiphere*/channellist.lua?select=json`

**Comment by hitam4450** [comment]
The firmware is **Version 1.0.55**

the response of the URL:
**404 not found**

I did a channel scan in the Panasonic TV....

How to initiate a channel scan in the OCTOPUSNET ??

an update check resulted in the message:

no update available!

regards, hitam4450
![octopusnet1055](https://cloud.githubusercontent.com/assets/9738727/24198571/b25ded0e-0f06-11e7-9ee7-0b35888b3d19.png)

**Comment by julianscheel** [comment]
That firmware is way outdated and lacks support for channel and epg scan, which is required for the kodi plugin to work. I think `1.0.80` is the latest. Are you sure your Octopus NET has working internet connectivity including a working DNS?

**Comment by hitam4450** [comment]
I connect the OCTOPIUSNET via static IP to my home network and i checked P, Gateway and netmask are OK. I was wondering myself already, that no new firmware was available, since I bought the OCTOPUSNET in the beginning of last year.

How to make it connect it to the Internet and how to update the firmware ???

regards, hitam4450

enclosed screen shot  of telnet session:

![o](https://cloud.githubusercontent.com/assets/9738727/24240512/3353cd7e-0fb2-11e7-98df-3618dea2478e.png)

Message from the system
![o1](https://cloud.githubusercontent.com/assets/9738727/24240631/a77eb3ee-0fb2-11e7-9266-70861c70934f.png)

Advice for static IP from official support:
![o3](https://cloud.githubusercontent.com/assets/9738727/24243631/087651ee-0fbc-11e7-9dc1-b2119d6bdbfd.png)

**Comment by JoergRoesner** [comment]
Hi,

here you can find the update procedure with a static IP.

http://support.digital-devices.eu/knowledgebase.php?article=170

regards Jörg

**Comment by hitam4450** [comment]
@JoergRoesner 

Thanks for your advice and reply:

Emclosed screen shot describes my current situation:

![o4](https://cloud.githubusercontent.com/assets/9738727/24243923/21758fd8-0fbd-11e7-8d3e-23cc78e9ebe4.png)


Of course , I could create a resolv.conf in /etc  !

**Comment by hitam4450** [comment]
Ok, the update of the firmware worked out fine! Many thanks for your advice!

regards, hitam4450
