### ISSUE TITLE
Add of Nexus branch and related version

### ISSUE THREAD

**Issue by AlwinEsch** [DigitalDevices/pvr.octonet#51]
Since Kodi 20 Nexus has been available for a some months now, it is time to create an associated Nexus branch and release for all addons, for this then maybe "20.0.0-Nexus" for here (relates to you, on Kodi side, addon major equal to Kodi major).

I'm doing this at all addons where I have access, but you would have to make a change to this one.

**Comment by da-anda** [comment]
could anyone please close this issue? It's resolved. Thanks.
