### ISSUE TITLE
add EPG support

### ISSUE THREAD

**Issue by da-anda** [DigitalDevices/pvr.octonet#64]
the octonet servers have support for EPG, which can be fetched from the device as JSON (IIRC). So it would be nice to also get the available EPG info imported into KODI

**Comment by ksooo** [comment]
The addon already supports this feature. If the server delivers epg data, the addon will hand them over to kodi.

**Comment by da-anda** [comment]
well, I have EPG in the webinterface of the device, but not in KODI, never had, not with the "legacy" firmware, nor with the new one

**Comment by ksooo** [comment]
It's been a while, but I know that the add-on fetches EPG data from the device and that they show up in Kodi.

What is missing ((at least when I last checked)  is that the device itself automatically initially requests and then regularly refreshes the EPG data. Once you fetched them manually via the web interface of the device, they will be available in Kodi automatically, but over time you will end with an empty EPG in Kodi.

As far as I remember, there is no API the add-on could call to request the device to refetch EPG data.

**Comment by da-anda** [comment]
ok, odd. Will check again. The URL the add-on fetches has EPG data in it, but as mentioned, I have never seen any EPG with this add-on in KODI. But maybe some settings are off then (but EPG is there via tvh, so no idea).

**Comment by ksooo** [comment]
Just checked with Kodi 20.4 - seems to work.

<img width="900" alt="Screenshot 2024-02-17 at 11 34 05" src="https://github.com/DigitalDevices/pvr.octonet/assets/3226626/8f234b15-2c02-434e-83df-82a057fde6d7">

![screenshot00004](https://github.com/DigitalDevices/pvr.octonet/assets/3226626/28dbe545-1d72-448e-93a7-a96040208849)

**Comment by da-anda** [comment]
hmm, ok. So you are running the old firmware still. Will check again later. Btw, new firmware looks a lot nicer:
![image](https://github.com/DigitalDevices/pvr.octonet/assets/1159249/2b83728c-fc26-4559-a3b2-5cce62cb61b6)

**Comment by ksooo** [comment]
I tried the new firmware, but found that tuning is (sometimes) significant slower with it, so switched back the legacy firmware which works just fine for me.
